dist: trusty
compiler: gcc

services:
  - docker

notifications:
  email: false

addons:
  apt:
    packages:
      - wget

matrix:
  include:
    - env: DOCKER_IMAGE=archlinux/base BUILD_SCRIPT=dist/docker_build_arch.sh
      name: "arch package build"
    - env: DOCKER_IMAGE=debian:stable BUILD_SCRIPT=dist/docker_build_deb.sh PKG_VERSION_POSTFIX=debian-stable
      name: "debian stable package build"
    - env: DOCKER_IMAGE=ubuntu:bionic BUILD_SCRIPT=dist/docker_build_deb.sh PKG_VERSION_POSTFIX=ubuntu-bionic
      name: "ubuntu bionic package build"
script:
  - docker run -v $PWD:/sources -w /sources -e PKG_VERSION_POSTFIX="$PKG_VERSION_POSTFIX" "$DOCKER_IMAGE" "$BUILD_SCRIPT"

after_success:
  - ls -lh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh appimage-firstrun*
