dist: trusty
compiler: gcc

services:
  - docker

notifications:
  email: false

addons:
  apt:
    packages:
      - wget
matrix:
  include:
    - env: DOCKER_IMAGE=archlinux/base BUILD_SCRIPT=dist/docker_build_arch.sh PACKAGE_EXTENSION=".pkg.tar.xz"
      name: "arch package build"
    - env: DOCKER_IMAGE=debian:stable BUILD_SCRIPT=dist/docker_build_deb.sh PACKAGE_EXTENSION=".deb"
      name: "deb package build"
script:
  - docker run -v $PWD:/sources -w /sources "$DOCKER_IMAGE" "$BUILD_SCRIPT"

after_success:
  - ls -lh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh "appimage-firstrun*$PACKAGE_EXTENSION"
